"""Sports Big Board v4 catalog contract.

The v4 catalog separates immutable-ish source-media identity from associations to
sporting events and editorial collections. Version fields intentionally live in
the persisted catalog so future classifiers/matchers can selectively re-evaluate
only rows produced by older logic.
"""

CATALOG_SCHEMA_VERSION = 4
MEDIA_CLASSIFIER_VERSION = 7
EVENT_MATCHER_VERSION = 7
RANKING_VERSION = 6
VERIFICATION_VERSION = 4

ASSIGNED = "ASSIGNED"
QUARANTINED = "QUARANTINED"
UNASSIGNED = "UNASSIGNED"
ASSOCIATION_STATES = {ASSIGNED, QUARANTINED, UNASSIGNED}

INTENT_RECAP = "RECAP"
INTENT_CONDENSED_GAME = "CONDENSED_GAME"
INTENT_EXTENDED_HIGHLIGHTS = "EXTENDED_HIGHLIGHTS"
INTENT_HIGHLIGHT = "HIGHLIGHT"
INTENT_TOP_PLAYS = "TOP_PLAYS"
INTENT_PLAYER_HIGHLIGHTS = "PLAYER_HIGHLIGHTS"
INTENT_INTERVIEW = "INTERVIEW"
INTENT_ANALYSIS = "ANALYSIS"
INTENT_PRESS_CONFERENCE = "PRESS_CONFERENCE"
INTENT_FULL_GAME = "FULL_GAME"
INTENT_OTHER = "OTHER"
VALID_MEDIA_INTENTS = {
    INTENT_RECAP, INTENT_CONDENSED_GAME, INTENT_EXTENDED_HIGHLIGHTS,
    INTENT_HIGHLIGHT, INTENT_TOP_PLAYS, INTENT_PLAYER_HIGHLIGHTS,
    INTENT_INTERVIEW, INTENT_ANALYSIS, INTENT_PRESS_CONFERENCE,
    INTENT_FULL_GAME, INTENT_OTHER,
}
