const fs=require('fs');
const assert=require('assert');
const VERSION=fs.readFileSync('VERSION','utf8').trim();
const parts=VERSION.split('.').map(Number);
const index=fs.readFileSync('index.html','utf8');
const nativeTransport=fs.readFileSync('architecture/native-transport.js','utf8');
const availability=fs.readFileSync('architecture/score-card-availability-index.js','utf8');
const render=fs.readFileSync('architecture/render-pipeline.js','utf8');
const efficiency=fs.readFileSync('architecture/efficiency-certification.js','utf8');
assert.deepStrictEqual(parts.slice(0,2),[4,7]);assert(parts[2]>=12);
assert(index.includes(`architecture/native-transport.js?v=${VERSION}`));
assert(index.indexOf(`architecture/native-transport.js?v=${VERSION}`)<index.indexOf(`architecture/request-broker.js?v=${VERSION}`));
assert(nativeTransport.includes('capturedFetch'));
assert(availability.includes('canonical Day State eventPlans'));
assert(availability.includes('catalogPlanForScoreGame'));
assert(availability.includes('payload?.eventPlans'));
assert(availability.includes("kind:'day-state-plan'"));
assert(availability.includes('plan?.playable'));
assert(render.includes('perfStartedAt'));
assert(render.includes('perfFinishedAt'));
assert(efficiency.includes('window.SBB_NATIVE_TRANSPORT?.fetch'));
assert(efficiency.includes('function attributeLongTask'));
assert(efficiency.includes("'LONGEST TASKS'"));
console.log(`PASS: ${VERSION} retains v4.7.12 native transport + Day State render-model baseline`);
