const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'architecture','key-info-current-v520.js'),'utf8');
const dev=fs.readFileSync(path.join(root,'architecture','dev-mode.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
function need(ok,msg){if(!ok){console.error('FAIL',msg);process.exitCode=1;}else console.log('PASS',msg);}
need(js.includes("const VERSION='5.2.7'"),'Sports Ticker module is v5.2.7');
need(js.includes("engine:'RAF_CONTINUOUS'"),'ticker declares the continuous rAF engine');
need(js.includes('requestAnimationFrame(tickerFrame)'),'ticker uses one continuous requestAnimationFrame clock');
need(!js.includes('conveyorGroup.animate('),'segmented Web Animations restarts are retired');
need(js.includes('const DEFAULT_TUNING=Object.freeze({height:40,fontSize:10.5,lines:1,speed:30,gap:18})'),'calm 30px/s default tuning is defined');
need(js.includes('const TUNING_KEY=')&&js.includes('localStorage.setItem(TUNING_KEY'),'ticker tuning persists locally');
need(js.includes('Math.min(rawDt,40)'),'busy frames are capped instead of producing catch-up jumps');
need(js.includes('first.remove();appendNextNode();conveyorX+=step'),'stories recycle without restarting the animation clock');
need(js.includes('.key-info-item.breaking .key-info-type'),'BREAKING pill color remains restored');
need(js.includes('.key-info-item.transaction .key-info-type'),'TRANSACTION pill color remains restored');
need(js.includes('.key-info-item.record .key-info-type'),'RECORD pill color remains restored');
need(index.includes('id="sportsTickerHeight"'),'Dev utility exposes ticker height');
need(index.includes('id="sportsTickerFontSize"'),'Dev utility exposes headline font size');
need(index.includes('id="sportsTickerLines"'),'Dev utility exposes one/two-line mode');
need(index.includes('id="sportsTickerSpeed"'),'Dev utility exposes scroll speed');
need(index.includes('id="sportsTickerGap"'),'Dev utility exposes story spacing');
need(index.includes('id="sportsTickerCopyTuningBtn"'),'Dev utility can copy the chosen tuning values');
need(index.includes('id="sportsTickerAiRefreshBtn"'),'RUN SPORTS TICKER AI lives in the dedicated ticker utility');
need(!index.includes('id="devModeToggleBtn"'),'nested Settings Dev toggle is removed');
need(dev.includes('const CLICK_TARGET=5'),'global Dev Mode uses five brand clicks');
need(dev.includes("toggle('brand-five-click')"),'five brand clicks toggle the one global Dev authority');
need(dev.includes('for(const node of [root,body])')&&dev.includes("node.dataset.sbbDev='1'"),'global Dev state is mirrored to html and body');
need(dev.includes("window.dispatchEvent(new CustomEvent('sbb:dev-mode'"),'all Dev consumers receive one global event');
need(js.includes("'/api/sports-ticker/refresh'"),'manual Sports Ticker AI refresh remains wired');
need(js.includes('renderActiveSportKeyInformation=renderNoop')&&js.includes('refreshKeyInformation=refreshNoop'),'score-date legacy ticker entry points remain no-ops');
if(process.exitCode)process.exit(process.exitCode);
