'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'architecture/key-info-current-v520.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(src.includes("const VERSION='5.2.2'"));
assert(src.includes("'/api/current-news'"),'Key Info must use dedicated current-news read model');
assert(src.includes("const CACHE_KEY='sbb.current-news.v522'"),'last good current news should paint before network');
assert(src.includes('cachedRows()'),'browser current-news cache missing');
assert(src.includes('withToday'),'news rendering must be independent of historical browse date');
assert(!src.includes('SBB_SCORE_DATE?.subscribe'),'score/date changes must not drive current-news renders');
assert(!src.includes('No saved key-information'),'retired wording must not return');
assert(index.includes('architecture/key-info-current-v520.js?v=5.2.2'));
console.log('PASS v5.2.2 persistent current-news Key Info invariants');
