const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const core=fs.readFileSync('core-model.js','utf8');
const view=fs.readFileSync('ui/game-center-view.js','utf8');
assert(core.includes("NCAAF:{id:'NCAAF'"));
assert(core.includes("gameCenterProvider:'espn',gameCenterFallback:'espn'"));
assert(app.includes("!=='CFB'"));
assert(app.includes("if(lg==='CFB') return []"));
assert(!view.includes('Game Center is disabled for NCAAF'));
assert(!app.includes('Game Center is disabled for NCAAF'));
console.log('PASS v5.1.11 NCAAF ribbon retirement + Game Center frontend');
