'use strict';
const fs=require('fs'),assert=require('assert');
const v=fs.readFileSync('architecture/virtual-ribbon-v520.js','utf8');
const fast=fs.readFileSync('architecture/ribbon-fast-scroll-v5122.js','utf8');
assert(v.includes("const VERSION='5.2.2'"));
assert(v.includes("CACHE_NAME='sbb-ribbon-snapshots-v522'"));
assert(v.includes('snapshotFreshEnough'));
assert(v.includes('if(dayDistance(date)>-2)return'),'today/yesterday persistent cache guard missing');
assert(v.includes('fetchBundle(today())'),'recent prepared snapshots should prefill browser memory');
assert(fast.includes('native score-ribbon scroll compatibility bridge'),'legacy controller should remain inert');
assert(!/addEventListener\(['"]wheel/.test(fast));
assert(!/pointermove/.test(fast));
console.log('PASS v5.2.2 scroll ownership + current-safe cache');
