const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(require('path').join(__dirname,'..','architecture','foundation-certification.js'),'utf8');
const listeners={};
global.window={SBB_RELEASE_VERSION:'4.3.8',SBB_CORE:{version:'4.3.8'},SBB_MILESTONE:{browserRuntime:()=>({userAgent:'TestBrowser/1',browserBrands:[{brand:'TestBrowser',version:'1'}],platform:'test',visibility:'visible',online:true})}};
global.navigator={userAgent:'TestBrowser/1',platform:'test',vendor:'test',language:'en-US',onLine:true};
global.document={readyState:'loading',visibilityState:'visible',addEventListener:(n,fn)=>{listeners[n]=fn;},getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]};
vm.runInThisContext(source,{filename:'foundation-certification.js'});
const dev=window.SBB_FOUNDATION_CERTIFICATION._dev;
assert(dev&&typeof dev.collectErrorEvidence==='function');
const base={problemCounts:{errors:0,warnings:0,info:0},problems:[],recent:[],playback:{latest:{state:'playing',invariant:'OK'}},extra:{release:{versionMatch:true},history:{workers:{w:{healthy:true}}}},checks:[{ok:true}],version:'4.3.8',versionMatch:true,api:{}};
let e=dev.collectErrorEvidence({...base,problemCounts:{errors:1}}, {steps:[]});
assert.equal(e.actionableErrors.length,0);assert.equal(e.diagnosticMismatch,true,'count-only error must be advisory, not a blocker');
e=dev.collectErrorEvidence({...base,problemCounts:{errors:1},recent:[{at:10,level:'ERROR',category:'error',source:'browser',message:'ReferenceError: boom',data:{}}]}, {steps:[]});
assert.equal(e.actionableErrors.length,1);assert.equal(e.recoveredAdvisories.length,0,'real browser error must remain actionable');
e=dev.collectErrorEvidence({...base,problemCounts:{errors:1},recent:[{at:10,level:'ERROR',category:'unhandledrejection',source:'browser',message:'AbortError: The play() request was interrupted by a call to pause()',data:{}}]}, {steps:[{at:11000,status:'PASS',name:'playback: next clip transition',data:{state:'playing'}}]});
assert.equal(e.actionableErrors.length,0);assert.equal(e.recoveredAdvisories.length,1,'transient media interruption with proven later playback must be advisory');
e=dev.collectErrorEvidence({...base,problemCounts:{errors:1},recent:[{at:10,level:'ERROR',category:'unhandledrejection',source:'browser',message:'AbortError: The play() request was interrupted by a call to pause()',data:{}}]}, {steps:[]});
assert.equal(e.actionableErrors.length,1,'transient-looking error without recovery proof must remain actionable');
const tier=dev.tier1Evaluation({...base,problemCounts:{errors:1}}, {status:'PASS',steps:[{status:'PASS',name:'x',at:1}]}, Object.fromEntries(['release-handshake','playback-cycle','historical-read','operator-load','resource-modes','game-center','soundtrack','ui-responsiveness','regression-hardening'].map(id=>[id,{status:'PASS',detail:'ok'}])));
const clean=tier.gates.find(x=>x.id==='clean-errors');assert(clean&&clean.ok===true,'count-only error must not fail Tier 1');assert(tier.errorEvidence.diagnosticMismatch===true);assert(tier.snapshot.browser.userAgent==='TestBrowser/1');
console.log('PASS: v4.3.8 certification error evidence semantics');
