'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const ctx={console,Set,Map,Object,Array,String,Number,RegExp,window:null};ctx.window=ctx;
ctx.SBB_PLAYBACK_TRANSPORTS={playbackKey:a=>a.youtubeId?`youtube:${a.youtubeId}`:(a.mediaUrl?`direct:${a.mediaUrl}`:`id:${a.id}`),transportForAsset:()=> 'YOUTUBE',inAppPlayable:()=>true};
ctx.SBB_MEDIA_SCOPE={isGame:()=>true};
ctx.SBB_SPORT_MEDIA_POLICY={REQUEST:{QUICK:'QUICK',EXTENDED:'EXTENDED',COMMENTARY:'COMMENTARY',MOMENTS:'MOMENTS',ANY:'ANY'},policyFor:()=>({sourceWeights:{},quick:{},extended:{},commentary:{}}),durationScore:()=>0};
ctx.SBB_PROVIDER_HEALTH={score:()=>0};ctx.SBB_PLAYBACK_READINESS={eligible:()=>true,rankBonus:()=>0};
ctx.SBB_MEDIA_MANIFEST={_assets:[],ingest(_e,rows){this._assets=ctx.SBB_MEDIA_RESOLVER?ctx.SBB_MEDIA_RESOLVER.uniquePhysical(rows):rows;},playable(){return this._assets;},external(){return[];},availability(){return ctx.SBB_MEDIA_CLASSIFIER.availability(this._assets);}};
vm.createContext(ctx);
for(const file of ['architecture/media-classifier.js','architecture/media-resolver.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const q={id:'db-quick',youtubeId:'sameVid',title:'Game Highlights',overview:true,programType:'recap',durationSeconds:600,mediaObjective:'QUICK',verifiedPlayable:true};
const e={id:'db-purple',youtubeId:'sameVid',title:'Extended Game Highlights',overview:true,programType:'recap',durationSeconds:600,mediaObjective:'EXTENDED',verifiedPlayable:true};
assert.equal(ctx.SBB_MEDIA_CLASSIFIER.tier(q),'extended');
let r=ctx.SBB_MEDIA_RESOLVER.resolve({},'QUICK',{assets:[q,e]});
assert.equal(r.ranked.length,1,'same YouTube video must collapse to one physical candidate');
assert.equal(r.availability.green,false);assert.equal(r.availability.extended,true);
const poisonedA={id:'poison-a',youtubeId:'poisonVid',title:'Game Recap',overview:true,programType:'recap',durationSeconds:200,runtimeState:'failed'};
const poisonedB={id:'poison-b',youtubeId:'poisonVid',title:'Game Recap',overview:true,programType:'recap',durationSeconds:200};
assert.equal(ctx.SBB_MEDIA_RESOLVER.uniquePhysical([poisonedA,poisonedB])[0].runtimeState,'failed','duplicate provenance must not resurrect a failed physical asset');
const quick={id:'q',youtubeId:'quickVid',title:'Game Recap',overview:true,programType:'recap',durationSeconds:210,mediaObjective:'QUICK',verifiedPlayable:true};
const ext={id:'e',youtubeId:'extVid',title:'Extended Highlights',overview:true,programType:'recap',durationSeconds:650,mediaObjective:'EXTENDED',verifiedPlayable:true};
r=ctx.SBB_MEDIA_RESOLVER.resolve({},'QUICK',{assets:[ext,quick]});
assert.equal(r.primary.youtubeId,'quickVid','genuine distinct quick recap must beat extended recap');
assert.equal(r.availability.green,true);assert.equal(r.availability.extended,true);
console.log('PASS: v4.4.8 physical recap identity + quick/extended selection');
