const fs=require('fs');
const assert=require('assert');

const VERSION=fs.readFileSync('VERSION','utf8').trim();
const index=fs.readFileSync('index.html','utf8');
const render=fs.readFileSync('architecture/render-pipeline.js','utf8');
const coordinator=fs.readFileSync('architecture/date-transition-coordinator.js','utf8');
const day=fs.readFileSync('architecture/day-state.js','utf8');
const efficiency=fs.readFileSync('architecture/efficiency-certification.js','utf8');

assert.strictEqual(VERSION,'4.7.7');
assert(index.indexOf(`architecture/render-pipeline.js?v=${VERSION}`) <
       index.indexOf(`architecture/date-transition-coordinator.js?v=${VERSION}`));
assert(render.includes('beginGeneration'));
assert(render.includes('commitGeneration'));
assert(render.includes('generation-hold'));
assert(render.includes('generationCommit:true'));
assert(render.includes('DocumentFragment'));
assert(render.includes('document.createDocumentFragment()'));
assert(render.includes('fragmentCommits'));
assert(render.includes('buildMs'));
assert(render.includes('commitMs'));
assert(render.includes("emit('paint'"));
assert(render.includes('reasonCounts'));
assert(coordinator.includes('SBB_RENDER_PIPELINE?.beginGeneration'));
assert(coordinator.includes('SBB_RENDER_PIPELINE?.commitGeneration'));
assert(coordinator.includes('transition owns exactly one first-paint ribbon commit'));
assert(!coordinator.includes("withReason?.('cold-ribbon-fallback'"));
assert(day.includes("SBB_RENDER_PIPELINE.request('day-state-apply'"));
assert(day.includes("'RIBBON_RENDER_REQUEST'"));
assert(efficiency.includes('function ribbonFirstUsable'));
assert(efficiency.includes('function ribbonFullySettled'));
assert(efficiency.includes('firstPaintMs'));
assert(efficiency.includes('settleTimeout'));
assert(efficiency.includes('FULL_SETTLE_TIMEOUTS='));
assert(efficiency.includes('CARD_BUILD_P95='));
assert(efficiency.includes('DOM_COMMIT_P95='));
assert(efficiency.includes('BROWSER_PAINT_P95='));
assert(efficiency.includes('RENDER_REASONS='));
console.log('PASS: v4.7.7 first-paint certification + generation render consolidation contracts');
