'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const VERSION=fs.readFileSync(path.join(root,'VERSION'),'utf8').trim();
assert.equal(VERSION,'5.0.5');
global.window=global;
vm.runInThisContext(fs.readFileSync(path.join(root,'architecture/curated-media-overrides.js'),'utf8'),{filename:'architecture/curated-media-overrides.js'});
assert.equal(SBB_CURATED_MEDIA.version,'1.0');
const usc={competitionId:'CFB',eventId:'401864494',espnEventId:'401864494',date:'2026-08-29T20:30:00Z',awayTeam:{name:'San José State Spartans',abbreviation:'SJSU'},homeTeam:{name:'USC Trojans',abbreviation:'USC'}};
const curated=SBB_CURATED_MEDIA.itemsFor(usc);
assert.equal(curated.length,1);
assert.equal(curated[0].youtubeId,'-tDiPDHU2fs');
assert.equal(curated[0].verifiedPlayable,true);
assert.equal(curated[0].__sbbCuratedOverride,true);
assert.equal(curated[0].recapTier,'green');
const merged=SBB_CURATED_MEDIA.apply(usc,[{id:'bad-direct',mediaUrl:'https://example.invalid/bad.mp4',verifiedPlayable:true}]);
assert.equal(merged[0].youtubeId,'-tDiPDHU2fs','curated asset must lead the media plan');
assert.equal(SBB_CURATED_MEDIA.preferred(usc,merged).youtubeId,'-tDiPDHU2fs');
assert.equal(SBB_CURATED_MEDIA.itemsFor({...usc,eventId:'different',espnEventId:'different',date:'2026-08-30'}).length,0,'override must not leak to another date/event');
const fixtures=SBB_CURATED_MEDIA.regressionFixtures();
assert(fixtures.some(x=>x.id==='cfb-2026-08-29-sjsu-usc-recap'&&x.youtubeIds.includes('-tDiPDHU2fs')));

const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const cert=fs.readFileSync(path.join(root,'architecture/comprehensive-site-certification.js'),'utf8');
assert(index.includes(`architecture/curated-media-overrides.js?v=${VERSION}`));
assert(index.indexOf(`architecture/curated-media-overrides.js?v=${VERSION}`)<index.indexOf(`architecture/media-manifest.js?v=${VERSION}`));
for(const token of ['SBB_CURATED_MEDIA?.apply?.(match','SBB_CURATED_MEDIA?.preferred?.(match','curatedOverrideId'])assert(app.includes(token),token);
assert(!app.includes('-tDiPDHU2fs'),'event-specific override data belongs in the registry, not app.js');
assert(cert.includes("const VERSION='3.5'"));
for(const token of ['curatedMediaRegression','CURATED MEDIA REGRESSION','CURATED_MEDIA attempted=','regressionFixtures'])assert(cert.includes(token),token);
assert(!cert.includes('401864494'),'whole-site certification must consume generic curated fixtures rather than hard-code USC');
console.log('PASS: v5.0.5 curated event-media override + deterministic regression fixture');
