'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'architecture/virtual-ribbon-v520.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(src.includes("const VERSION='5.2.2'"));
assert(src.includes('const VIRTUAL_THRESHOLD=96'),'ordinary large days should not recycle while scrolling');
assert(src.includes('rows.slice(win.start,win.end)'),'extreme days must remain virtualized');
assert(src.includes("host.addEventListener('wheel',onWheel,{passive:false,capture:true})"),'one ribbon wheel bridge must own horizontal mouse-wheel motion');
assert(src.includes('wheelPending+=delta*2.65'),'mouse wheel needs a snappy horizontal multiplier');
assert(src.includes('requestAnimationFrame(()=>'),'wheel writes must be frame-budgeted');
assert(src.includes("clone.dataset.warmSchedulerWired='1'"),'legacy scroll-triggered media warm listener must be blocked before attachment');
assert(src.includes("current.replaceWith(clone)"),'existing anonymous legacy scroll listener must be removed');
assert(src.includes('if(currentRows.length>32)'),'large ribbons must skip background media priming');
assert(!src.includes("window.addEventListener('scroll'"),'vertical page scroll cannot schedule ribbon work');
assert(!src.includes('content-visibility:auto'),'vertical page scrolling must not trigger first-entry layout hitches');
assert(src.includes('/api/ribbon-snapshot/bundle'),'recent date bank must hydrate in one request');
assert(src.includes('const BUNDLE_PAST=14'));
assert(index.includes('architecture/virtual-ribbon-v520.js?v=5.2.2'));
assert(index.indexOf('date-transition-coordinator.js?v=5.2.2') < index.indexOf('virtual-ribbon-v520.js?v=5.2.2'));
console.log('PASS v5.2.2 interaction-priority ribbon invariants');
